name: GiftD CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start the app
        run: npm run dev &
        env:
          PORT: 5173

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:5173
          timeout: 30

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 60